locale = "en"
site_title = "Montelibero"
site_subtitle = "Free Society Project in Europe"
meta_description = "Project by Third Fund Of Montelibero"
project_of_tfm = "Project by Third Fund Of Montelibero"
join_telegram = "Join Telegram group"

[what_is_montelibero]
header = "What is Montelibero?"
text = """
Montelibero is a social experiment to move libertarians to Montenegro and build a free society in Montenegro on libertarian principles.

What are those principles? In a nutshell: free market and non-aggression.

If you value human life, honour private property, respect other people's skills and honest business, only want the state to get behind you, and generally believe that states create more problems than they solve - it is quite likely that you are a libertarian, even if this is the first time you have read this word.
"""

[population]
header = "Community growth"
text = """
The first Montelibero settlers arrived in Montenegro in December 2021. The sharp growth of the community happened after the beginning of the hot phase of the war in Ukraine. Now the inflow of emigrants from Russia has slowed down and we are mainly growing with the diaspora. We are also being joined by people from over-regulated EU countries, primarily Germany.
"""

[growth]
header = "Development"
text = """
Libertarianism is about the entrepreneurial spirit. In a free market, the more you succeed, the more you benefit others. Success can be in terms of money or social capital.

Many of the Montelibero participants have already launched one business or another.On a separate wiki page (link) we have tried to list those we have mentioned. If you have forgotten someone, just put yourself there.

But there are many projects where the focus is not on profit, but on improving the infrastructure of Montelibero. More about them later, but for now a few words about our economic engine:
"""

[tokenomics]
header = "Tokenomics"
text = """
What it is. In short: it is an economy based on the exchange of tokens, i.e. entries in a public register describing certain property rights. It is better to get acquainted with a more detailed description (link to the article about tokenomics), it will be useful to you anyway.

We try to describe almost all our economic relations through tokenomics. Why?Because it turned out to be a convenient bridge between online and offline, because the project participants live not only in Montenegro, but all over the world.

Now let's get back to infrastructure projects
"""

[eurmtl]
header = "EURMTL"
text = """
Montenegro uses the euro, but the country is not officially part of the eurozone. Therefore, banking functionality here is rather modest. EURMTL is our euro-stablecoin, which we use among ourselves instead of cash. For example, to split a cheque in a cafe.

EURMTL's collateral is ordinary euro cash, which is held by our treasurers.

Their duties include storing the cache, exchanging it round trip for EURMTL without commission, and periodically auditing it. Some of the EURMTL is backed in excess by other liquid assets like bitcoin.
"""

[MTL]
header = "MTL"
text = """
In the early days of Montelibero, money in the project was scarce, so we put it into a common cube, our investment fund. MTL tokens are shares in the fund. The fund coordinates the EURMTL system and many other tokenomics instruments. It is managed by the top twenty shareholders.

The main task of the fund is to attract money from all over the world and invest it in the development of the Montelibero project - both in business and infrastructure.
"""

[meetings]
header = "MTL-breakfasts Ð¸ lunches"
text = """
While the Montelibero Investment Fund raises money from all over the world, in Montenegro itself, activists are attracting people who have heard something about the project and would like to meet them. Once a week there is a MTL breakfast, and once a week there is a MTL lunch. People gather in cafes, get to know each other, chat informally, ask questions about the project, and see how our tokenomics works in everyday calculations. And then at some point they start talking about libertarians and the Montelibero project, not "they" but "we".
"""

[fcm]
header = "First Club of Montelibero"
text = """
It's not enough for people to know they are libertarians.It is also important for them to be among like-minded people.This is the strongest incentive to join the community.Rare meetings in cafes are not enough for that.

The First Club of Montelibero is a place where libertarians feel at home. So, sorry, not everyone becomes a resident of the club. First a person comes as a guest invited by one of the residents. Then they get acquainted with him and decide whether to accept him into the club.
"""

[city]
header = "MTL-City"
text = """
Spending evenings at the club is great, but why shouldn't libertarians settle in the neighbourhood?

In the summer of 2021, the MTL Foundation and a few private individuals bought a hectare of land.Then divided it amongst themselves in proportion to their investment.Cleared it. Built a road. They put in electricity and internet. They built a reservoir and a sewerage system. And, of course, they started building houses.

At the end of May 2023, the first permanent resident appeared in MTL-City. In the middle of 2023, two residential buildings were completed: a three-storey eight-apartment building on the land of the Foundation and a glamping house "geosphere" on one of the private plots.

Construction continues.
"""

[mtlfest]
header = "MTL-Fest"
text = """
On 23 September 2023, the first libertarian festival in Montenegro took place in MTL City, which has all chances to become an annual event.

At the festival there were: a lecture hall, a music programme, a sports programme, a children's playground (we are Ancaps, and we love children). Also, of course, a food court, a separate area for tent camping, a fair, a pre-party and after-party, where without them.

[Read more on the festival website](https://mtlfest.me)
"""

[online]
header = "Online activities"
text = """
We haven't told you about Montelibero and a tenth of it. If you'd like to know more, we look forward to hearing from you on our many online platforms.

Radio Montelibero is a regular podcast covering community life, challenges, achievements, a look at what's going on around you and ideas for the future. (TODO: links to the different platforms).

And direct online communication between members - old-timers and newcomers alike - takes place in numerous themed Telegram channels and chat rooms (and there's also a forum for those who appreciate unhurried, structured communication formats). On the wiki page we have collected links to those info-resources that we remembered. If you have been forgotten, you know what to do.
"""

[join]
header = "Okay, that's really cool, how do I join you?"
text = """
There are plenty of options scattered throughout the text above, for a wide variety of participation levels! Subscribe to channels, talk in chat rooms, set up a wallet, get the tokens you are most interested in, come to Montenegro, come meet people at breakfasts and lunches, come as a guest to a club, become a resident of a club, come to a festival, start a business, start an activity that will attract many other community members... All avenues are open!
"""